export class Clientes {
  constructor
  (
    nombres='',
  apellidos='',
  tipo_documento='',
  numero_documento='',
  direccion='',
  telefono='',
  celular='',ruc='',dni=''
  )
  {
    this.nombres=nombres;
    this.apellidos=apellidos;
    this.tipo_documento=tipo_documento;
    this.numero_documento=numero_documento;
    this.direccion=direccion;
    this.telefono=telefono;
    this.celular=celular;
    this.ruc=ruc
    this.dni=dni
  }
  id_clientes:string;
  nombres:string;
  apellidos:string;
  tipo_documento: string;
  numero_documento:string
  direccion:string;
  telefono:string
  celular:string
  ruc:string
  dni:string
}
